apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: apps
  namespace: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    id: basic
    realm: basic
    enabled: true
    displayName: Basic Realm
